CREATE TYPE difficulty_type AS ENUM ('normal', 'nightmare', 'hell');

ALTER TABLE characters ADD area integer;
ALTER TABLE characters ADD difficulty difficulty_type;
ALTER TABLE characters ADD players integer;
ALTER TABLE characters ADD hc boolean;
ALTER TABLE characters ADD lod boolean;
ALTER TABLE characters ADD dead boolean;
ALTER TABLE characters ADD deaths integer;
ALTER TABLE characters ADD fcr integer;
ALTER TABLE characters ADD frw integer;
ALTER TABLE characters ADD fhr integer;
ALTER TABLE characters ADD ias integer;
ALTER TABLE characters ADD mf integer;
ALTER TABLE characters ADD gold_total integer;
ALTER TABLE characters ADD seconds_played integer;
ALTER TABLE characters ADD in_game_time integer;
-- ALTER TABLE characters ADD finish_time integer;
ALTER TABLE characters ADD disqualified boolean;
ALTER TABLE characters ADD town_visits integer DEFAULT 0;
ALTER TABLE characters ADD finished_normal_quests integer DEFAULT 0;
ALTER TABLE characters ADD finished_nightmare_quests integer DEFAULT 0;
ALTER TABLE characters ADD finished_hell_quests integer DEFAULT 0;
ALTER TABLE characters ADD total_kills integer DEFAULT 0;
ALTER TABLE characters ADD animal_kills integer DEFAULT 0;
ALTER TABLE characters ADD undead_kills integer DEFAULT 0;
ALTER TABLE characters ADD demon_kills integer DEFAULT 0;
ALTER TABLE characters ADD champion_kills integer DEFAULT 0;
ALTER TABLE characters ADD unique_kills integer DEFAULT 0;

ALTER TABLE characters ADD d2_mod text;
ALTER TABLE characters ADD d2_version text;
ALTER TABLE characters ADD d2_args text;
